[package]
name = "extract-google-photos"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
indicatif = "0.17.11"
regex = "1.11.1"
walkdir = "2.5.0"
